"""adds __repr__to freebie

Revision ID: 4ce56f263101
Revises: 19183079f74b
Create Date: 2024-09-11 05:42:30.560340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce56f263101'
down_revision = '19183079f74b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
