"""Finishes All Models

Revision ID: 9924474f0e62
Revises: fd6bd8697a37
Create Date: 2024-09-11 06:10:33.639482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9924474f0e62'
down_revision = 'fd6bd8697a37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
