"""Finishes Freebie Model

Revision ID: fd6bd8697a37
Revises: 4ce56f263101
Create Date: 2024-09-11 06:01:51.637275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6bd8697a37'
down_revision = '4ce56f263101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
